@startuml
hide footbox

box "Client"
participant "Application" as AP
participant "Scripting API" as SA
end box

box "Server(Thing)"
participant "WoT Server" as WS
participant "Device" as DC
end box

AP  -> SA: calls \n thing.writeProperty()
activate SA
SA  -> AP: returns Promise
SA  -> WS: sends HTTP PUT Request to href of form \n (body: schema data)
activate WS
WS <-> DC: sets Property value \n to corresponding device
WS  -> SA: sends back HTTP PUT Response
deactivate WS
SA  -> AP: calls back Promise \n resolving to void
deactivate SA
@enduml
