@startuml
hide footbox

box "WoT Client"
participant "Application" as AP
participant "Consumed Thing" as SA
end box

box "WoT Server"
participant "Exposed Thing" as WS
participant "Application" as DC
end box

AP  -> SA: invoke\n"writeproperty"\noperation
activate SA
SA  -> AP: returns Promise
SA  -> WS: send HTTP PUT Request\nto href of form\n(body: schema data)
activate WS
WS <-> DC: set\nProperty value
WS  -> SA: send HTTP PUT Response
deactivate WS
SA  -> AP: Promise callback\n (resolves to: void)
deactivate SA
@enduml
